### PR TITLE
Gradle file changes 

### PR DESCRIPTION
**Pull request by mddanishansari**
Please review the changes and merge ASAP as they are creating problems in Android Studio while compiling.

Making the changes manually in './node_modules' is okay, but everytime you try to delete and again do 'npm install' the problem occurs again.

### CODE REVIEW

**Comment by jpshelley** [comment]
@mddanishansari what is your build output in Studio? And what is your compile SDK?

**Comment by mddanishansari** [comment]
My compile SDK version is 27 but soon I'll update it to 28

Following is my build output

```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-android-fragment


WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-android-fragment


WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-android-fragment


WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: react-native-android-fragment
```

**Comment by jpshelley** [comment]
@mddanishansari We'll be updating to sdk 28 soon at Hudl as well. When that happens we'll push to update this repo as well. As of right now those are only Warnings though and the build should still compile.

**Comment by mddanishansari** [comment]
@jpshelley thanks a lot

**Comment by jpshelley** [comment]
@mddanishansari Thanks for suggesting this request. We'll be officially deprecating this repo now that Hudl has upgraded and can take advantage of `react-native`'s official [ReactFragment](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactFragment.java)

If you believe the official `ReactFragment` also needs this support I would suggest opening a PR there! https://github.com/facebook/react-native/pulls

**Pull request closed without merging**
